#!/bin/bash

# Vercel Environment Variables Setup Script
# Run this to add required environment variables to Vercel

echo "🔧 Setting up Vercel environment variables..."
echo ""
echo "⚠️  IMPORTANT: You need to add these environment variables in Vercel Dashboard:"
echo ""
echo "================================================"
echo "REQUIRED DATABASE VARIABLES:"
echo "================================================"
echo ""
echo "1. DATABASE_URL (Required)"
echo "   Description: Pooled PostgreSQL connection for serverless functions"
echo "   Example: postgresql://user:pass@host-pooler.region.provider.com/db?pgbouncer=true&sslmode=require"
echo ""
echo "2. DIRECT_URL (Required)"
echo "   Description: Direct PostgreSQL connection for migrations"
echo "   Example: postgresql://user:pass@host.region.provider.com/db?sslmode=require"
echo ""
echo "================================================"
echo "OTHER REQUIRED VARIABLES:"
echo "================================================"
echo ""
echo "3. NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
echo "4. CLERK_SECRET_KEY"
echo "5. NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in"
echo "6. NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up"
echo "7. NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard"
echo "8. NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard"
echo ""
echo "================================================"
echo "OPTIONAL VARIABLES:"
echo "================================================"
echo ""
echo "9. RESEND_API_KEY (for email notifications)"
echo "10. CONTACT_EMAIL (for contact form)"
echo ""
echo "================================================"
echo "HOW TO ADD IN VERCEL:"
echo "================================================"
echo ""
echo "Via Vercel CLI:"
echo "  vercel env add DATABASE_URL production"
echo "  vercel env add DIRECT_URL production"
echo ""
echo "Via Vercel Dashboard:"
echo "  1. Go to https://vercel.com/dashboard"
echo "  2. Select your project"
echo "  3. Go to Settings → Environment Variables"
echo "  4. Add each variable with 'Production' environment selected"
echo "  5. Redeploy from Deployments tab"
echo ""
echo "================================================"
echo "AFTER ADDING VARIABLES:"
echo "================================================"
echo ""
echo "1. Redeploy your application"
echo "2. Check deployment logs for any errors"
echo "3. Test the health endpoint: https://your-app.vercel.app/api/health"
echo ""
